apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: resumetask
  name: resumetask
spec:
  template:
     spec:
       containers:
       - image: jasvinder1107/resumecliimage:latest
         imagePullPolicy: Always
         name: resumetask
         command: ["/tmp/start.sh"]
         volumeMounts:
         - mountPath: /resultpath
           name: result-vol
       restartPolicy: Never
       volumes:
       - name: result-vol
         hostPath:
           path: /root/resume-result
           type: Directory
status: {}
